name: CanvasBrowser
options:
  bundleIdPrefix: com.canvas
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO

targets:
  CanvasBrowser:
    type: application
    platform: macOS
    sources:
      - path: CanvasBrowser
        excludes:
          - "**/*.entitlements"
          - "Resources/Entitlements.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.canvas.browser
        INFOPLIST_FILE: CanvasBrowser/Info.plist
        PRODUCT_NAME: "Canvas Browser"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: NO
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - target: CanvasBrowserWidgets
        embed: true
    postBuildScripts:
      - script: |
          # Sign the app for local development
          codesign --force --deep --sign - "${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}"
        name: Sign App
        runOnlyWhenInstalling: false

  CanvasBrowserWidgets:
    type: extensionkit-extension
    platform: macOS
    sources:
      - path: CanvasBrowserWidgets
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.canvas.browser.widgets
        INFOPLIST_FILE: CanvasBrowserWidgets/Info.plist
        PRODUCT_NAME: CanvasBrowserWidgets
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
          - "@executable_path/../../../../Frameworks"
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        SWIFT_EMIT_LOC_STRINGS: YES

schemes:
  CanvasBrowser:
    build:
      targets:
        CanvasBrowser: all
        CanvasBrowserWidgets: all
    run:
      config: Debug
      executable: CanvasBrowser
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
